apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
        rolearn: arn:aws:iam::563286812971:role/UdacityFlaskDeployCBKubectlRole
        username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::563286812971:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1X3HPHO3O9VU8
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-27T18:49:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1817"
  uid: dbd1604a-d404-4db1-9361-33840066b5b3
